bin/dev-setup.sh
update fees sql
```
[ ] Yes
[ ] No
```
=> update fees sql

bin/ccd-add-all-roles.sh, bin/idam-client-setup.sh
https://tools.hmcts.net/jira/browse/DTSPB-24
Update roles and idam client setup
```
[ ] Yes
[x] No
```
=> DTSPB-24 update roles

bin/idam-role-assignable.sh
https://tools.hmcts.net/jira/browse/DTSPB-24
update idam assignable roles
```
[ ] Yes
[x] No
```
=> Dtspb 24 update roles

bin/dev-setup.sh, package.json
https://tools.hmcts.net/jira/browse/DTSPB-1251
Fix fees issue - retry up[dates
```
[ ] Yes
[x] No
```
=> DTSPB-1187 - fix fees issue

bin/dev-setup.sh, package-lock.json, package.json
Fix fees - attempt sql updates after fees api restarted - records it is trying to update do not exist
```
[ ] Yes
[x] No
```
=> move fee sql updates

bin/dev-setup.sh, bin/dev-start.sh
move fee updates to dev start, as in setup, we are trying to update a row before it is inserted
```
[ ] Yes
[x] No
```
=> move fee updates to dev start

package-lock.json, package.json
update version numbers
```
[ ] Yes
[x] No
```
=> update version numbers

bin/dev-setup.sh, package-lock.json, package.json
remove duplicate code
```
[ ] Yes
[x] No
```
=> remove duplicate code

bin/dev-start.sh, package-lock.json, package.json
Allow fees longer for update to work
```
[ ] Yes
[x] No
```
=> allow longer for fee updates

bin/dev-start.sh
remove volume amount update as this succeeds in npx create
```
[ ] Yes
[x] No
```
=> remove volume amount update as it succeeded previously

bin/dev-setup.sh, package-lock.json, package.json
Amend volume_amount id from 4 to 5
```
[ ] Yes
[x] No
```
=> change volume_amount id to 5

bin/dev-start.sh, package-lock.json, package.json
add volume_amount update to dev start
```
[ ] Yes
[x] No
```
=> add volume amount update to devstart

bin/dev-setup.sh, bin/dev-start.sh
=> amend sql command to pick up correct volume_amount

package-lock.json, package.json
=> update version num

bin/dev-setup.sh, bin/dev-start.sh
=> DTSPB-1571: try update fees again

bin/insert-fees.sh, package-lock.json, package.json
=> DTSPB-1571: trying to tag correctly

bin/dev-setup.sh, bin/dev-start.sh
=> Dtspb 1571 update fees data

package-lock.json, package.json
=> DTSPB-1571: rearranged fees insert and update - version update

bin/dev-start.sh, bin/insert-fees.sh, package-lock.json, package.json
=> DTSPB-1571: corrected SAL5K fee

bin/ccd-add-all-roles.sh, bin/idam-client-setup.sh, bin/idam-xui-user-token.sh, bin/xui-add-role.sh, package.json
DTSPB-1704
Add xui changes without any curl changes
```
[ ] Yes
[ X ] No
```
=> DTSPB-1704 Add xui changes without any curl changes

bin/dev-start.sh, package.json
N/A
set BIN_FOLDER variable to fix wiremock.sh
```
[ ] Yes
[x] No
```
=> set BIN_FOLDER variable to fix wiremock.sh

bin/ccd-add-all-roles.sh, bin/idam-client-setup.sh, package.json
N/A
Add ccd system user 
```
[ ] Yes
[x] No
```
=> Add ccd system user
